---
- name: Python Setup
  hosts: all
  become: yes
  tasks:
  - name: Update apt
    apt:
      update_cache: yes

  - name: Install Nginx
    apt:
      name: nginx
      state: latest
    
  - name: Install Python
    apt:
      name: python3
      state: present

  - name: Install Python3-pip
    apt:
      name: python3-pip
      state: latest


